package constants

const (
	LogUserRegisterSuccess       = "user register success: username=%s"
	LogUserRegisterFailed        = "user register failed: username=%s"
	LogUserLoginSuccess          = "user login success: username=%s"
	LogUserLoginFailed           = "user login failed: username=%s"
	LogUserProfileUpdated        = "user profile updated: user_id=%d"
	LogUniversityCreateSuccess   = "university created: name=%s"
	LogUniversityCreateFailed    = "university create failed: name=%s"
	LogUniversityUpdateSuccess   = "university updated: id=%d"
	LogUniversityListSuccess     = "university list success: country=%s"
	LogAppCreateSuccess          = "application project created: id=%d major=%s"
	LogAppCreateFailed           = "application project create failed: major=%s"
	LogAppStatusChanged          = "application status changed: id=%d status=%s"
	LogAppStatusChangeFailed     = "application status change failed: id=%d"
	LogDocumentSaveSuccess       = "document saved: id=%d version=%d"
	LogDocumentSaveFailed        = "document save failed: id=%d"
	LogDocumentVersionCreated    = "document version created: document_id=%d version_no=%d"
	LogAnnotationCreateSuccess   = "annotation created: document_id=%d"
	LogMaterialCreateSuccess     = "material item created: application_id=%d name=%s"
	LogMaterialStatusChanged     = "material status changed: id=%d status=%s"
	LogTimelineCreateSuccess     = "timeline node created: application_id=%d title=%s"
	LogTimelineDone              = "timeline node done: id=%d"
	LogRecommendationCreate      = "recommendation created: student_id=%d"
	LogMessageSendSuccess        = "message sent: sender=%d receiver=%d"
	LogMessageRead               = "message marked read: id=%d"
	LogDeadlineReminderSent      = "deadline reminder sent: node_id=%d"
	LogUploadSuccess             = "file upload success: object=%s"
	LogUploadFailed              = "file upload failed: filename=%s"
	LogRateLimited               = "request rate limited: path=%s ip=%s"
	LogRequestHandled            = "request handled: request_id=%s method=%s path=%s status=%d latency_ms=%d"
)
